# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

##
trigger:
- main
pool:
      name: default



steps:
  - task: JFrogDocker@1
    inputs:
      command: 'Pull'
      artifactoryConnection: 'kimt'
      imageName: 'morielp-docker/postgres'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      includeEnvVars: true
      skipLogin: false
  - task: JFrogDocker@1
    inputs:
      command: 'Scan'
      xrayConnection: 'kimt-xray'
      imageName: 'morielp-docker/postgres'
      watchesSource: 'watches'
      watches: 'morielp-azure-docker'
      allowFailBuild: true
      allowBypassArchiveLimits: false
      threads: '3'
      skipLogin: false








